IMAGE_WIDTH=$1
IMAGE_HEIGHT=$1
SVG_DIR=$2
OUTPUT_DIR=$3

if [ -d $OUTPUT_DIR ]
then
  rm -rf $OUTPUT_DIR
fi

mkdir -p $OUTPUT_DIR

for SVGFILE in ${SVG_DIR}/*.svg;
do
  SVG_FILENAME=`basename ${SVGFILE}`
  PNG_FILENAME=${SVG_FILENAME%.svg}.png
  OUTPUT_FILE=${OUTPUT_DIR}/${PNG_FILENAME}
  rsvg-convert -w $IMAGE_WIDTH -h $IMAGE_HEIGHT $SVGFILE -o ${OUTPUT_FILE}
  echo OUTPUT_FILE=${OUTPUT_FILE}
done
