on:
  schedule:
    - cron:  '0 12 * * *'

name: on-schedule
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: install librsvg2-bin
      run: sudo apt-get install librsvg2-bin
    - name: build.sh
      run: ./build.sh
    - name: count PNG files
      run: find . -name *.png | wc -l
    - name: count PNG files
      run: find . -name *.png | wc -l
    - name: Git Add
      run:  git add docs
    - name: Git Commit
      run:  git commit -m "update"
    - name: Git Push
      run:  git push
