on:
  schedule:
    - cron:  '0 12 * * *'

name: on-schedule
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: install librsvg2-bin
      run: sudo apt-get install librsvg2-bin
    - name: build.sh
      run: ./build.sh
    - name: count PNG files
      run: find . -name *.png | wc -l
    - name: Git commit
      run: |
        git config --global user.name "GitHub Actions"
        git add docs
        git commit -m "update" || echo "No changes to commit"
        git push origin HEAD:main
